//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bodega_Manager.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura_Detail
    {
        public int Id { get; set; }
        public Nullable<int> Id_Factura_Header { get; set; }
        public Nullable<int> Codigo_Repuesto { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Tag_Maquina { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual Factura_Header Factura_Header { get; set; }
        public virtual Repuesto Repuesto1 { get; set; }
        public virtual Maquina Maquina1 { get; set; }
    }
}
