//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bodega_Manager.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura_Header
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura_Header()
        {
            this.Factura_Detail = new HashSet<Factura_Detail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Codigo_Mecanico { get; set; }
        public Nullable<decimal> Costo_Total { get; set; }
        public Nullable<int> Cantidad_Repuestos { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura_Detail> Factura_Detail { get; set; }
        public virtual Mecanico Mecanico1 { get; set; }
    }
}
