//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bodega_Manager.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repuesto_Data
    {
        public int Id { get; set; }
        public Nullable<int> Codigo_Repuesto { get; set; }
        public Nullable<int> Min { get; set; }
        public Nullable<int> Max { get; set; }
        public Nullable<int> Promedio { get; set; }
    
        public virtual Repuesto Repuesto { get; set; }
    }
}
