//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bodega_Manager.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repuesto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Repuesto()
        {
            this.Repuesto_Data = new HashSet<Repuesto_Data>();
            this.Factura_Detail1 = new HashSet<Factura_Detail>();
        }
    
        public int Id { get; set; }
        public int Codigo { get; set; }
        public string Codigo_Lawson { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Cantidad_Stock { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public string Localidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repuesto_Data> Repuesto_Data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura_Detail> Factura_Detail1 { get; set; }
    }
}
